#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="rocketchat"

sleep 6

mkdir -p \
            /app/uploads \
            /tmp/.container \
            /tmp/userData/

chown -R node \
                /app \
                /tmp/userData

db_ready mongo

liftoff
