#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="rocketchat"

sleep 6
mkdir -p /app/uploads
chown -R rocketchat /app/uploads
mkdir -p /tmp/state/
mkdir -p /tmp/userData/
chown -R rocketchat /tmp/userData

db_ready mongo

liftoff