### Application Level Image CI
### Dave Conroy <dave at tiredofit dot ca>

name: 'build'


on:
  schedule:
    - cron: 0 3 * * 5
  push:
    paths:
    - '**'
    - '!README.md'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        id: prep
        run: |
          git clone "https://github.com/RocketChat/Rocket.Chat" rocketchat
          ROCKETCHAT_VERSION=$(git -C ./rocketchat tag | sort -V | tail -n 1 | sed "s|-.*||g")
          DOCKER_IMAGE=${GITHUB_REPOSITORY/docker-/}
          CHANGELOG_VERSION=$(head -n 1 CHANGELOG.md | awk '{print $2'})

          if [[ $GITHUB_REF == refs/heads/* ]]; then
             if [[ $GITHUB_REF == refs/heads/*/* ]] ; then
               BRANCH="${DOCKER_IMAGE}:$(echo $GITHUB_REF | sed "s|refs/heads/||g" | sed "s|/|-|g")"
             else
               BRANCH=${GITHUB_REF#refs/heads/}
             fi

            case ${BRANCH} in
              "main" | "master" )
                  BRANCHTAG="${DOCKER_IMAGE}:${ROCKETCHAT_VERSION}-${CHANGELOG_VERSION}"
                ;;
              "develop" )
                  BRANCHTAG="${DOCKER_IMAGE}:develop"
                ;;
              * )
                  if [ -n "${{ secrets.LATEST }}" ] ; then
                    if [ "${BRANCHTAG}" = "${{ secrets.LATEST }}" ]; then
                      BRANCHTAG="${DOCKER_IMAGE}:${BRANCH},${DOCKER_IMAGE}:${BRANCH}-latest,${DOCKER_IMAGE}:latest"
                    else
                      BRANCHTAG="${DOCKER_IMAGE}:${BRANCH},${DOCKER_IMAGE}:${BRANCH}-latest"
                    fi
                  else
                    BRANCHTAG="${DOCKER_IMAGE}:${BRANCH},${DOCKER_IMAGE}:${BRANCH}-latest"
                  fi
                ;;
            esac
          fi

          TAGS="${BRANCHTAG}${GITTAG}"

          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Modify
        id: modify
        run: |
          git clone --depth 1 https://github.com/tiredofit/docker-alpine docker-alpine
          sed -i "s|FROM .*|FROM rocketchat/rocket.chat:4.8.6-alpine|g" ./docker-alpine/Dockerfile
          sed -i "/FROM .*/a USER root" ./docker-alpine/Dockerfile
          sed -i 's|IMAGE_NAME="tiredofit/alpine"|IMAGE_NAME="tiredofit/rocketchat"|g' ./docker-alpine/Dockerfile
          sed -i 's|IMAGE_REPO_URL="https://github.com/tiredofit/docker-alpine/"|IMAGE_REPO_URL="https://github.com/tiredofit/docker-rocketchat/"|g' ./docker-alpine/Dockerfile
          cp -R install docker-alpine/
          mkdir -p docker-alpine/install/assets/.changelogs
          cp -R docker-alpine/CHANGELOG.md docker-alpine/install/assets/.changelogs/tiredofit_docker-alpine.md

      - name: Label
        id: Label
        run: |
          if [ -f "./docker-alpine/Dockerfile" ] ; then
            sed -i "/FROM .*/a LABEL tiredofit.image.git_repository=\"https://github.com/${GITHUB_REPOSITORY}\"" ./docker-alpine/Dockerfile
            sed -i "/FROM .*/a LABEL tiredofit.image.git_commit=\"${GITHUB_SHA}\"" ./docker-alpine/Dockerfile
            sed -i "/FROM .*/a LABEL tiredofit.image.git_committed_by=\"${GITHUB_ACTOR}\"" ./docker-alpine/Dockerfile
            sed -i "/FROM .*/a LABEL tiredofit.image.image_build_date=\"$(date +'%Y-%m-%d %H:%M:%S')\"" ./docker-alpine/Dockerfile
            if [ -f "CHANGELOG.md" ] ; then
              sed -i "/FROM .*/a LABEL tiredofit.image.git_changelog_version=\"$(head -n1 ./CHANGELOG.md | awk '{print $2}')\"" ./docker-alpine/Dockerfile
              mkdir -p docker-alpine/install/assets/.changelogs ; cp CHANGELOG.md docker-alpine/install/assets/.changelogs/${GITHUB_REPOSITORY/\//_}.md
            fi

            if [[ $GITHUB_REF == refs/tags/* ]]; then
              sed -i "/FROM .*/a LABEL tiredofit.image.git_tag=\"${GITHUB_REF#refs/tags/v}\"" ./docker-alpine/Dockerfile
            fi

            if [[ $GITHUB_REF == refs/heads/* ]]; then
              sed -i "/FROM .*/a LABEL tiredofit.image.git_branch=\"${GITHUB_REF#refs/heads/}\"" ./docker-alpine/Dockerfile
            fi
          fi

      - name: Build
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./docker-alpine/
          file: ./docker-alpine/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.prep.outputs.tags }}

