### Application Level Image CI
### Dave Conroy <dave at tiredofit dot ca>

name: 'build'


on:
  schedule:
    - cron: 0 3 * * 5
  push:
    paths:
    - '**'
    - '!README.md'
jobs:
  image_build:
    env:
      docker_distro: docker-alpine
      build_file: Dockerfile

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        id: prep
        run: |
          git clone "https://github.com/RocketChat/Rocket.Chat" rocketchat
          ROCKETCHAT_VERSION=$(git -C ./rocketchat tag | sort -V | tail -n 1 | sed "s|-.*||g")
          CHANGELOG_VERSION=$(head -n 1 CHANGELOG.md | awk '{print $2'})

          if [[ "${GITHUB_REF}" == refs/heads/* ]]; then
              if [[ "${GITHUB_REF}" == refs/heads/*/* ]] ; then
                  git_branch="${GITHUB_REPOSITORY/docker-/}:$(echo $GITHUB_REF | sed "s|refs/heads/||g" | sed "s|/|-|g")"
              else
                  git_branch=${GITHUB_REF#refs/heads/}
              fi

              case "${git_branch}" in
                  "main" | "master" )
                      branch_tag="${GITHUB_REPOSITORY}:latest"
                      BRANCHTAG="${GITHUB_REPOSITORY}:${ROCKETCHAT_VERSION}-${CHANGELOG_VERSION}"
                  ;;
                  "develop" )
                      branch_tag="${GITHUB_REPOSITORY}:develop"
                  ;;
                  * )
                      if [ -n "${{ secrets.LATEST }}" ] || [ -n "${{ env.LATEST }}" ]; then
                          if [ "${branch_tag}" = "${{ secrets.LATEST }}" ] || [ "${{ env.LATEST }}" = "TRUE" ] ; then
                              branch_tag="${GITHUB_REPOSITORY}:${git_branch},${GITHUB_REPOSITORY}:${git_branch}-latest,${GITHUB_REPOSITORY}:latest"
                          else
                              branch_tag="${GITHUB_REPOSITORY}:${git_branch},${GITHUB_REPOSITORY}:${git_branch}-latest"
                          fi
                      else
                          branch_tag="${GITHUB_REPOSITORY}:${git_branch},${GITHUB_REPOSITORY}:${git_branch}-latest"
                      fi
                  ;;
              esac
          fi

          if [ -n "${branch_tag}" ] && [ -n "${git_tag}" ]; then
              image_tags=${branch_tag},${git_tag}
          else
              image_tags="${branch_tag}${git_tag}"
          fi

          echo "dockerhub_repo=${GITHUB_REPOSITORY/docker-/}" >> $GITHUB_ENV
          dockerhub_images=$(echo "${image_tags}" | sed "s|${GITHUB_REPOSITORY}|docker.io/${GITHUB_REPOSITORY/docker-/}|g")
          ghcr_images=$(echo "${image_tags}" | sed "s|${GITHUB_REPOSITORY}|ghcr.io/${GITHUB_REPOSITORY}|g")
          echo "container_images=${dockerhub_images},${ghcr_images}" >> $GITHUB_OUTPUT

          git clone --depth 1 https://github.com/tiredofit/${{ env.docker_distro }} ${{ env.docker_distro }}
          sed -i "s|FROM .*|FROM rocketchat/rocket.chat:${ROCKETCHAT_VERSION}-$(echo ${docker_distro} | sed "s|docker-||g")|g" ./${{ env.docker_distro }}/${{ env.build_file }}
          sed -i "/FROM .*/a USER root" ./${{ env.docker_distro }}/${{ env.build_file }}
          sed -i "s|IMAGE_NAME=.*|IMAGE_NAME=\"tiredofit/rocketchat\" \\\|g" ./${{ env.docker_distro }}/${{ env.build_file }}
          sed -i "s|${{ env.docker_distro }}/${{ env.build_file }}|docker-rocketchat|g" ./${{ env.docker_distro }}/${{ env.build_file }}
          cp -R install ${{ env.docker_distro }}/
          mkdir -p ${{ env.docker_distro }}/install/assets/.changelogs
          cp -R ${{ env.docker_distro }}/CHANGELOG.md ${{ env.docker_distro }}/install/assets/.changelogs/tiredofit_${{ env.docker_distro }}.md

      - name: Label
        id: Label
        run: |
          image_name=${GITHUB_REPOSITORY/docker-/}
          if [ -f "${{ env.build_file }}" ] ; then
              sed -i "/FROM .*/a LABEL tiredofit.${image_name}.git_repository=\"https://github.com/${GITHUB_REPOSITORY}\"" ${{ env.docker_distro }}/${{ env.build_file }}
              sed -i "/FROM .*/a LABEL tiredofit.${image_name}.git_commit=\"${GITHUB_SHA}\"" ${{ env.docker_distro }}/${{ env.build_file }}
              sed -i "/FROM .*/a LABEL tiredofit.${image_name}.git_committed_by=\"${GITHUB_ACTOR}\"" ${{ env.docker_distro }}/${{ env.build_file }}
              sed -i "/FROM .*/a LABEL tiredofit.${image_name}.image_build_date=\"$(date +'%Y-%m-%d %H:%M:%S')\"" ${{ env.docker_distro }}/${{ env.build_file }}
              sed -i "/FROM .*/a LABEL org.opencontainers.image.source https://github.com/${GITHUB_REPOSITORY}"  ${{ env.docker_distro }}/${{ env.build_file }}

              if [ -f "CHANGELOG.md" ] ; then
                sed -i "/FROM .*/a LABEL tiredofit.${image_name}.git_changelog_version=\"$(head -n1 ./CHANGELOG.md | awk '{print $2}')\"" ${{ env.docker_distro }}/${{ env.build_file }}
                mkdir -p install/assets/.changelogs ; cp CHANGELOG.md install/assets/.changelogs/${GITHUB_REPOSITORY/\//_}.md
              fi

              if [[ $GITHUB_REF == refs/tags/* ]]; then
                sed -i "/FROM .*/a LABEL tiredofit.${image_name}.git_tag=\"${GITHUB_REF#refs/tags/v}\"" ${{ env.docker_distro }}/${{ env.build_file }}
              fi

              if [[ $GITHUB_REF == refs/heads/* ]]; then
                sed -i "/FROM .*/a LABEL tiredofit.${image_name}.git_branch=\"${GITHUB_REF#refs/heads/}\"" ${{ env.docker_distro }}/${{ env.build_file }}
              fi
          fi

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm,arm64

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./${{ env.docker_distro }}/${{ env.build_file }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.prep.outputs.container_images }}

      - name: Update Docker Hub Information
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.dockerhub_repo }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.md
